apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  labels:
    app: {{ .Chart.Name }}
type: Opaque
data:
  POSTGRESPASSWORD: T0FjUmlOa0FUSElEZVJ5QUdPQW1hQ0hlYUxP
  POSTGRESHOST: bXNjc3R1ZGVudHMuY2huYmJpeHFoZTY3LmV1LXdlc3QtMi5yZHMuYW1hem9uYXdzLmNvbQ==
  POSTGRESUSER: c3R1ZGVudA==
  POSTGRESDB: ZGVtb2FwaQ==